### PR TITLE
Pug support

### LINKED ISSUE #83: Jade is depricated
grunt-html2js has a dependency for jade ^1.3.1 which now deprecated:

npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade

### PR DESCRIPTION
**Pull request by tyriker**
This is @bennorwood's work from his original PR #89 (thanks Ben!)

I took his fork and made sure it worked for me (I need Pug processing in html2js), then rebased it with the latest from rquadling/grunt-html2js/master to resolve the existing conflicts, then made sure it still worked.

Submitting this PR to hopefully get Pug support added officially (even if still in beta), and partially resolve #83 (it doesn't remove Jade).

This PR may be easier to merge since PR #89 now contains conflicts.

### CODE REVIEW

**Comment by bennorwood** [comment]
Thanks? It was pretty trivial to fix the merge issues; you could have commented on my PR for the update.

**Comment by tyriker** [comment]
No problem... In my experience, maintainers often don't consider PRs with merge conflicts, and since I'd pulled your fork down already for testing, I simply rebased it, resolved, and pushed it back upstream. The commits are all still yours! 😄

**Comment by Sjors** [comment]
Fwiw, I was able to use this succesfully by putting `"grunt-html2js": "WeWriteCode/grunt-html2js#pug-support",` in my `package.json` file.

**Comment by rquadling** [comment]
@tyriker Can you please handle the merge conflicts for this pull request.

**Comment by bennorwood** [comment]
@rquadling this is the same work in https://github.com/rquadling/grunt-html2js/pull/89

**Comment by tyriker** [comment]
@rquadling @bennorwood 
It looks like #89 has already been merged, which is the same fix/code. This can just be closed.

**Pull request closed without merging**
